class APIStatus{
    createLink="#created";
    noContentLink="#no-content";
    movedLink="#moved";
    badRequestLink="#bad-request";
    unauthorizedLink="#unauthorized";
    forbiddenLink="#forbidden";
    invalidUrlLink="#invalid-url";
    statusMessage="#linkResponse";
    clickOnCreateLink()
    {
        cy.get(this.createLink).click()
    }
    clickOnNoContentLink()
    {
        cy.get(this.noContentLink).click()
    }
    clickOnMovedLink()
    {
        cy.get(this.movedLink).click()
    }
    clickOnBadRequestLink()
    {
        cy.get(this.badRequestLink).click()
    }
    clickOnUnauthorizedLink()
    {
        cy.get(this.unauthorizedLink).click()
    }
    clickOnForbiddenLink()
    {
        cy.get(this.forbiddenLink).click()
    }
    clickOnInvalidUrlLink()
    {
        cy.get(this.invalidUrlLink).click()
    }
    verifyStatusMessage(value)
    {
        cy.get(this.statusMessage).should("have.text",value)
    }
 }
 export default APIStatus;