class WebTable{
        selectRow(dropDownValue,rowCount)
       {
           cy.get("select")
           .select(dropDownValue)
           .invoke("val")
           .should("eq", rowCount)
     } 
        clickOnAdd() 
     {
            cy.get("#addNewRecordButton").click()
        }
        verifyRegistrationForm(headerOfRegistration)
        {
            cy.get("#registration-form-modal").should('contain.text',headerOfRegistration)
        }
        setFirstName(firstName)
        {
            cy.get("#firstName").type(firstName).should("have.value",firstName)
        }
        setLastName(lastName)
        {
            cy.get("#lastName").type(lastName).should("have.value",lastName)
        } 
        setEmailId(emailId)
        {
            cy.get("#userEmail").type(emailId).should("have.value",emailId)
        }
        setAge(age)
        {
            cy.get("#age").type(age).should("have.value",age)
        }
        setsalary(salary)
        {
            cy.get("#salary").type(salary).should("have.value",salary)
        }
        setDepartment(department)
        {
            cy.get("#department").type(department).should("have.value",department)
        }
        clickSubmit()
       {
        cy.get("#submit").click()
       }
       searchUserFirstName(name)
       {
        cy.get("#searchBox").type(name)
       }
      clickOnEditIcon()
      {
        cy.get("span[title='Edit']").click()
      }
       verifyFirstName(firstName)
        {
            cy.get("#firstName").should("have.value",firstName)
        }
        verifyLastName(lastName)
        {
            cy.get("#lastName").should("have.value",lastName)
        } 
        verifyEmailId(emailId)
        {
            cy.get("#userEmail").should("have.value",emailId)
        }
        verifyAge(age)
        {
            cy.get("#age").should("have.value",age)
        }
        verifysalary(salary)
        {
            cy.get("#salary").should("have.value",salary)
        }
        verifyDepartment(department)
        {
            cy.get("#department").should("have.value",department)
        }
        clickOnDeleteIcon()
      {
        cy.get("span[title='Delete']").click()
      }
        

 }
 export default WebTable;